name: flutter_naver_maps_api
description: flutter implementation for naver maps api!
version: 0.0.1
homepage: https://github.com/bamnenim/flutter_naver_maps_api

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1 